on:
    issues:
        types: [assigned]
    issue_comment:
        types: [created]
    pull_request:
        types: [closed]

jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        
        # https://github.com/robvanderleek/create-issue-branch
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@v1.4
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
