on:
  push:
    branches:
      - main

name: Build and Deploy to Google Cloud

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_BUCKET_ID: ${{ secrets.GCP_BUCKET_ID }}
  IMAGE: octochat
  GCP_REGION: us-central1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Authenticate with gcloud credentials
      - name: Configure Google Cloud credentials
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
        with:
          version: 275.0.0
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}

      # Set up Docker
      - run: |
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build
        run: |
          docker build -t gcr.io/"$GCP_PROJECT"/"$IMAGE"/"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" 

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA

      # Deploy to Google Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $IMAGE \
            --service-account ${{ secrets.GCP_EMAIL }} \
            --project $GCP_PROJECT \
            --image gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA \
            --platform managed \
            --region $GCP_REGION \
            --set-env-vars "APP_ID=berglas://${GCP_BUCKET_ID}/app_id,CLIENT_ID=berglas://${GCP_BUCKET_ID}/client_id,CLIENT_SECRET=berglas://${GCP_BUCKET_ID}/client_secret,SESSION_STORE_SECRET=berglas://${GCP_BUCKET_ID}/session_store,REDIRECT_URI=berglas://${GCP_BUCKET_ID}/redirect_uri" \
            --allow-unauthenticated
